---
- name: K8S | namespace | create 
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    api_version: v1
    kind: namespace
    name: "{{ item }}"
  with_items: "{{ project_environment_list }}"
  tags:
    - initialize_k8s
    - initialize_k8s_namespace

- name: K8S | namespace | create | new
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    api_version: v1
    kind: namespace
    name: "{{ namespace }}"
  tags:
    - k8s_namespace
    - k8s_namespace_create
