---
- name: K8S | secret | folder
  file: 
    path: secret/{{ item }}
    state: directory
  with_items:
    - "{{ project_environment_list }}"
  tags:
    - initialize_k8s
    - initialize_k8s_secret
    - initialize_k8s_secret_folder

- name: K8S | secret | create | postgresql
  shell: bash secrets_gen/postgresql.sh {{ item[1] }} {{ item[0] }} `openssl rand -base64 12`
  with_nested:
    - "{{ project_api_list }}"
    - "{{ project_sharedb_list }}"
  tags:
    - initialize_k8s
    - initialize_k8s_secret
    - initialize_k8s_secret_postgresql

- name: K8S | secret | apply | postgresql
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    src: secret/{{ item[1] }}/{{ item[0] }}-postgresql.yml
  with_nested:
    - "{{ project_api_list }}"
    - "{{ project_environment_list }}"
  tags:
    - initialize_k8s
    - initialize_k8s_secret
    - initialize_k8s_secret_postgresql

- name: K8S | secret | create | postgresql | project
  shell: bash secrets_gen/postgresql.sh {{ item }} {{ project }} `openssl rand -base64 12`
  with_items:
    - "{{ project_sharedb_list }}"
  tags:
    - k8s_project
    - k8s_project_secret
    - k8s_project_secret_postgresql

- name: K8S | secret | apply | postgresql | project
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    src: secret/{{ item }}/{{ project }}-postgresql.yml
  with_items:
    - "{{ project_environment_list }}"
  tags:
    - k8s_project
    - k8s_project_secret
    - k8s_project_secret_postgresql

- name: K8S | secret | create | redis
  shell: bash secrets_gen/redis.sh {{ item[1] }} {{ item[0] }} `openssl rand -hex 12`
  with_nested:
    - "{{ project_api_list }}"
    - "{{ project_sharedb_list }}"
  tags:
    - initialize_k8s
    - initialize_k8s_secret
    - initialize_k8s_secret_redis

- name: K8S | secret | apply | redis
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    src: secret/{{ item[1] }}/{{ item[0] }}-redis.yml
  with_nested:
    - "{{ project_api_list }}"
    - "{{ project_environment_list }}"
  tags:
    - initialize_k8s
    - initialize_k8s_secret
    - initialize_k8s_secret_redis

- name: K8S | secret | create | redis | project
  shell: bash secrets_gen/redis.sh {{ item }} {{ project }} `openssl rand -hex 12`
  with_items:
    - "{{ project_sharedb_list }}"
  tags:
    - k8s_project
    - k8s_project_secret
    - k8s_project_secret_redis

- name: K8S | secret | apply | redis | project
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    src: secret/{{ item }}/{{ project }}-redis.yml
  with_items:
    - "{{ project_environment_list }}"
  tags:
    - k8s_project
    - k8s_project_secret
    - k8s_project_secret_redis

- name: K8S | secret | create | rabbitmq
  shell: bash secrets_gen/rabbitmq.sh {{ item[1] }} {{ item[0] }} `openssl rand -hex 12` `openssl rand -hex 12`
  with_nested:
    - "{{ project_rabbitmq_list }}"
    - "{{ project_sharedb_list }}"
  tags:
    - initialize_k8s
    - initialize_k8s_secret
    - initialize_k8s_secret_rabbitmq

- name: K8S | secret | apply | rabbitmq
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    src: secret/{{ item[1] }}/{{ item[0] }}-rabbitmq.yml
  with_nested:
    - "{{ project_rabbitmq_list }}"
    - "{{ project_environment_list }}"
  tags:
    - initialize_k8s
    - initialize_k8s_secret
    - initialize_k8s_secret_rabbitmq

- name: K8S | secret | create | general
  shell: bash secrets_gen/{{ item }}.sh
  with_items:
    - "{{ project_environment_list }}"
  tags:
    - initialize_k8s_secret_general

- name: K8S | secret | apply | general
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition: "{{ lookup('file', '{{ item }}.yml') | from_yaml }}"
  with_items:
    - "{{ project_environment_list }}"
  tags:
    - initialize_k8s
    - initialize_k8s_secret
    - initialize_k8s_secret_general
