---
- name: K8S | storageDeployment | create 
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition: "{{ lookup('template', 'nfs-deployment.yml') | from_yaml }}"
  tags:
    - initialize_k8s
    - initialize_k8s_storage

- name: K8S | storageClass | create 
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition: "{{ lookup('template', 'nfs-class.yml') | from_yaml }}"
  tags:
    - initialize_k8s
    - initialize_k8s_storage