apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nfs-client-provisioner
  namespace: kube-public
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: default
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: domain.self/data/nfs
            - name: NFS_SERVER
              value: {{ nfs_server }}
            - name: NFS_PATH
              value: {{ nfs_server_path }}
      volumes:
        - name: nfs-client-root
          nfs:
            server: {{ nfs_server }}
            path: {{ nfs_server_path }}
