apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ project }}-{{ project_type }}"
  namespace: "{{ namespace }}"
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi