apiVersion: v1
kind: Service
metadata:
  name: "{{ item[0] }}-api"
  namespace: "{{ item[1] }}"
  labels:
    app: "{{ item[0] }}-api"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: "{{ item[0] }}-api"
