apiVersion: v1
kind: Service
metadata:
  name: "{{ item[0] }}-rabbitmq"
  namespace: "{{ item[1] }}"
  labels:
    app: "{{ item[0] }}-rabbitmq"
spec:
  type: ClusterIP
  ports:
  - name: epmd
    port: 4369
    targetPort: epmd
  - name: amqp
    port: 5672
    targetPort: amqp
  - name: dist
    port: 25672
    targetPort: dist
  - name: stats
    port: 15672
    targetPort: stats
  selector:
    app: "{{ item[0] }}-rabbitmq"
