apiVersion: v1
kind: Service
metadata:
  name: "{{ item[0] }}-postgresql"
  namespace: "{{ item[1] }}"
  labels:
    app: "{{ item[0] }}-postgresql"
spec:
  type: ClusterIP
  ports:
  - name: postgresql
    port: 5432
    targetPort: postgresql
  selector:
    app: "{{ item[0] }}-postgresql"