---
- name: hostname | modify /etc/hostname
  shell: echo {{ inventory_hostname }} > /etc/hostname
  tags:
    - initialize
    - initialize_hosts
    - initialize_hosts_rename

- name: hostname | apply /etc/hostname
  shell: hostname -b -F /etc/hostname
  tags:
    - initialize
    - initialize_hosts
    - initialize_hosts_rename

- name: hosts | apply /etc/hosts
  template: src=hosts dest=/etc/hosts
  tags:
    - initialize
    - initialize_hosts
    - initialize_hosts_update

- name: nscd | install package
  apt: name=nscd
       state=latest
  tags:
    - initialize
    - initialize_hosts
    - initialize_hosts_update

- name: nscd | restart | pick up changes to /etc/hosts
  service: name=nscd state=restarted
  ignore_errors: true
  tags:
    - initialize
    - initialize_hosts
    - initialize_hosts_update